export const MAKE_GUESS = 'MAKE_GUESS';
export const CONFIRM_CORRECT_GUESS = 'CONFIRM_CORRECT_GUESS';
export const CONFIRM_INCORRECT_GUESS = 'CONFIRM_INCORRECT_GUESS';
export const START_NEXT_ROUND = 'START_NEXT_ROUND';
export const SHOW_MODAL = 'SHOW_MODAL';
export const START_NEW_GAME = 'START_NEW_GAME';
